### ISSUE TITLE
Provide a demo merchant for testing

### ISSUE THREAD

**Issue by nsarno** [lnbits/nostrmarket#30]
I'm playing around with writing a lib for building a marketplace web client. So far I'm focusing on the ability to restore a merchant from a list of relays and a public key.

Do you have an existing demo merchant's pubkey I could use for testing? I could obviously create one myself, but it would defeat the purpose of validating that I'm following the correct event structure, etc.

I pushed a very basic draft at https://github.com/nsarno/nostr-market-js, any feedback welcome! I have basically no idea what I'm doing... :)

**Comment by talvasconcelos** [comment]
You can use this: `e90995db35870a26b9ca0a891844bd0a8e8c7f785d53b8f8e16fb7e215e2c966`

**Comment by nsarno** [comment]
Awesome, thank you. Which relays is this broadcasting to?
