### ISSUE TITLE
Store Wiped Nostr Profile Data

### ISSUE THREAD

**Issue by pardus79** [lnbits/nostrmarket#44]
Deployed a merchant and used my existing nostr privkey. The shop wiped my Nostr profile data.

Would prefer if the extension handled profiles like other Nostr clients do, where they pull data from relays and only push profile updates if changes are pushed. The extension should load my existing profile and only push if I actively make changes to it.

**Comment by motorina0** [comment]
Thank you for reporting. Issue fixed here: https://github.com/lnbits/nostrmarket/pull/46 and created release [v.0.2.5](https://github.com/lnbits/nostrmarket/releases/tag/v0.2.5).

The profile will not be updated from `nostrmarket` at this point.
However, if the merchant is deleted, then a delete event will be published.
