### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by callebtc** [lnbits/nostrmarket#45]
https://github.com/lnbits/lnbits-extensions/actions/runs/4734982979/jobs/8404641108

**Comment by motorina0** [comment]
License is there for a while. The GitHub actions have to be updated.

https://github.com/lnbits/nostrmarket/blob/main/LICENSE

**Comment by motorina0** [comment]
fixed here: https://github.com/lnbits/lnbits-extensions/pull/94/files
closing
