### ISSUE TITLE
Add build and contribution documentation to the readme / docs?

### ISSUE THREAD

**Issue by rabble** [lnbits/nostrmarket#47]
I just had two separate people ask me about marketplaces on nostr. But the docs here are not really there for how to build and test it and contribute.

**Comment by motorina0** [comment]
- there is a step-by-step user guide here: https://github.com/lnbits/nostrmarket#nostr-market
  - on how to create a merchant, stall, products
  - it includes the video `Demo at Nostrica`
- `nostrmarket` (this repo) is an LNbits extension
  - for how to install extensions see: https://github.com/lnbits/lnbits/wiki/LNbits-Extensions
- developing with LNbits: https://github.com/lnbits/lnbits/wiki/LNbits-Documentation#developing-with-lnbits
  - the sections are collapsed by default, make sure to expand them

Please let me know if can help with any info in particular (besides the generic documentation).

**Comment by arcbtc** [comment]
This is interesting, without knowing LNbits and that this is an extension for LNbits, I could imagine extension docs like this being disorientating. 
For people new to the LNbits project like @rabble, we should prob have in the head of all extension readmes `"This in an extension for LNbits"`
