### ISSUE TITLE
Escrow service

### ISSUE THREAD

**Issue by PatrickGeyer** [lnbits/nostrmarket#48]
What seems like the best way forward for escrow services nostr-wide?
Is Civ Kit the best proposal so far? https://github.com/civkit/paper/blob/main/civ_kit_paper.pdf

Or are there other solutions already being used?

**Comment by motorina0** [comment]
> What seems like the best way forward for escrow services nostr-wide?
- start a discussion on the nostr tg channel or make a NIP proposal

> Is Civ Kit the best proposal so far? 
- can't tell

> Or are there other solutions already being used?
- nostrmarket is pretty young, I don't think escrow services are being used atm
