### ISSUE TITLE
Feature request Reputation system on verified transactions

### ISSUE THREAD

**Issue by Koenig-Johannes** [lnbits/nostrmarket#51]
I would like to suggest a new feature that I believe would be valuable for both buyers and sellers. Specifically, I propose the implementation of a reputation system that would allow users to verify the authenticity of reviews by showing proof of purchase through transaction IDs.

Additionally, this feature could also be used to track the supply chain of products, providing an added layer of transparency for buyers. It would be particularly useful if users could filter reputations to only display reviews left by trusted sources such as friends, followers or trusted merchants maybe even on multiple levels.

**Comment by motorina0** [comment]
> verify the authenticity of reviews by showing proof of purchase
- the problem here is that the `client` and the `merchant` can collude (or be the same entity), so a multitude of **positive**  "verified reviews" can be produced with no cost

what was your approach to these issues?

**Comment by Koenig-Johannes** [comment]
To the best of my knowledge, any transaction involving trust is inevitable, which is why it is crucial to minimize it as much as possible. This approach becomes more logical when either the entire supply chain could be shown (i.e., you cannot sell what you do not own), or other factors such as the age of keys, following/followers, and number of posts are taken into account. One possible Approach could also be to adopt the GPG key approach to a decentralized web of trust.

I would love to see this implemented so that others can contribute with smart ideas on how to filter or even just provide filter so clients can set for them selfs.
