### ISSUE TITLE
Possibility to group merchants and their stalls into a "Shopping Mall"

### ISSUE THREAD

**Issue by Satoshi-Samourai** [lnbits/nostrmarket#52]
I would like to propose a feature that will allow LNBits super user or admin accounts to group other merchants on their LNBits instance into something like a "shopping mall". The super user/admin could than share a link/pubkey which makes shopping mall accessable to others wit one click.

For example different merchants in one specific city or area can be organized by one LNBits admin account and advertise their stalls in one regional group which could be called a "shopping mall".

Please, be aware that I am not a computer specialist, but I am placing this request because I have a use case for minimum 20 merchants in a certain European region. 

Thank you very much for considering.

**Comment by motorina0** [comment]
This is a valid usecase!
- however, this should be done one the `market` side (anyone) and not on the `merchant` side (lnbits admin only).
- currently on the `market` side (`https://somelnbits.xxx/nostrmarket/market`) the user can add as many merchants as it likes (aggregate them into a `marketplace` or `shopping mall`)

![image](https://user-images.githubusercontent.com/2951406/235852686-81285000-6283-4ea3-a22a-8c765b62f19a.png)

- the problem remains now on how to share this `marketplace` with others
- this PR solves part of the problem: https://github.com/lnbits/nostrmarket/pull/41
  - more merchant public keys can be aggregated in a `naddr` fields
  - therefore the link to a marketplace can be something of this form: `https://somelnbits.xxx/nostrmarket/market?config=naddr....`

@talvasconcelos 
  - can you please confirm the PR will cover this this scenario
  - how would one export from the marketplace the `naddr`?

**Comment by talvasconcelos** [comment]
That's correct! I'd say the URL should look like `https://somelnbits.xxx/nostrmarket/market?naddr=naddr....` though!

the event content for the "config" would look something like:
```
{
    "name": <string, marketplace name>,
    "about": <string>, // used for SEO/metadata stuff probably
    "merchants": <string list: of merchant public keys>,
    "ui" : {
      "picture": <url, string: the logo of the marketplace>,
      "banner": <string: URL to a banner image (250px height)>,
      "theme": <string: name of the default theme>,
    }
   ...
}
```

**Comment by Satoshi-Samourai** [comment]
@motorina0 , @talvasconcelos 

thank you very much for considering my suggestion.

I am totally agreeing that this should happen on the market side. I was rather thinking of an "open source" "local shopping mall" where everybody who is linked to
https://somelnbits.xxx/nostrmarket/market?naddr=naddr....   can add new "shopping mall" stalls./members.

Still some initial merchant/admin needed to create that local shopping mall, though. Could be even a "create new local shopping mall" button as in BTCMap "add new community".

I am new to Github, but still hope that all makes sense to you.

Thanks again. greetings.
