### ISSUE TITLE
Merchant stall / product not showing up in search 

### ISSUE THREAD

**Issue by sirsatsalot** [lnbits/nostrmarket#53]
Using LNbits I installed the Nostr Market plugin and follwed all the steps to make a merchant stall and product (socks). 

How do I get it to populate in a search or have a link to it or have it show up in nostr?

**Comment by sirsatsalot** [comment]
> > How do I get it to populate in a search or have a link to it or have it show up in nostr?
> 
> * the market client can be accessed as described here: https://github.com/lnbits/nostrmarket#diagon-alley-clients
> * then add the public key of your merchant:
>   ![image](https://user-images.githubusercontent.com/2951406/236166729-82019d14-59e5-4b0b-99a6-5e71af472343.png)

<img width="532" alt="image" src="https://user-images.githubusercontent.com/65477795/236529470-5c7591f7-1003-430b-b93f-cd42ddcc4eb6.png">

**Comment by arbadacarbaYK** [comment]
> How to add nostrclient? <img alt="image" width="219" src="https://user-images.githubusercontent.com/65477795/236528894-0c0a8e0f-1f67-425c-8afb-aa4d53d76df7.png"> I see it under the "installed" tab of "manage extensions" but not in my side bar. It doesn't show up in the "extensions" area

Installed means they are enabled for the users of your lnbits but not nessecarily activated for the superuser wallet yet. To activate them you need to go to extensions -> find nostr client -> set enable

**Comment by sirsatsalot** [comment]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/65477795/236649412-d801521b-7658-4f87-9a1b-0d5492817116.png">
nostr client isn't in the extensions

**Comment by arbadacarbaYK** [comment]
> <img alt="image" width="1434" src="https://user-images.githubusercontent.com/65477795/236649412-d801521b-7658-4f87-9a1b-0d5492817116.png">
> nostr client isn't in the extensions

It is under manage exstensions - installed. But on Legend its an admin-Exstension and you cannot use it to make relays there. Youll need your own lnbits. https://legend.lnbits.com/install?usr=840c08e56e5b48a99a502f52e02d2df4

**Comment by motorina0** [comment]
@sirsatsalot I have updated the `nostrmarket` documentation. I hope it helps.
- Prerequisites: https://github.com/lnbits/nostrmarket/blob/main/README.md#prerequisites
  - make sure nostrclient works as expected
- Troubleshoot: https://github.com/lnbits/nostrmarket/blob/main/README.md#troubleshoot
  - trying to fix the connection with Nostr
- Client: https://github.com/lnbits/nostrmarket/blob/main/README.md#diagon-alley-clients
  - make sure the merchant public key is correctly configured

**Comment by motorina0** [comment]
@sirsatsalot can we close this issue? Are you still experiencing problems?
