### ISSUE TITLE
[Feature request] Export option into csv

### ISSUE THREAD

**Issue by Darth-Coin** [lnbits/nostrmarket#54]
Please consider adding a simple button to export in csv file all the stall items and stall info if is possible,
Yes, we can restore from pubkey the merchant, but in the database remain nothing.

**Comment by motorina0** [comment]
With the new changes to the marketplace you will be able to restore from nostr your stalls and products.
Then you can update/delete them if you want. 

There changes are on `main` and there is a `pre-release` if you want to test:

OP: https://github.com/lnbits/nostrmarket/issues/61#issuecomment-1614450262

https://github.com/lnbits/nostrmarket/assets/2951406/d8389463-c63f-4a8b-8c0d-708b41d81fb1

**Comment by motorina0** [comment]
I think this option is better than the CSV approach.
However, there is a core-level task to backup & restore the DB of any extension.
