### ISSUE TITLE
BUG - Importing an npub shows "another merchant already uses this npub" (0.2.8)

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/nostrmarket#57]
This one is in use on legend and i wanted to import it on my own instance (Citadel 0.2.1)

<img width="652" alt="Bildschirmfoto 2023-05-07 um 20 16 06" src="https://user-images.githubusercontent.com/63317640/236696201-00f4992e-31aa-49f1-8d7e-6650c04c202f.png">

**Comment by motorina0** [comment]
Is it possible that you have tried to import it twice, for two different users?

**Comment by motorina0** [comment]
> generated on legend, wanted to "import" on my node´s lnbits

- I understand. But is it possible that you have already imported that merchant on your LNbits node (but for a different LNbits user)?
- do you have the possibility of executing SQL queries?  If yes, can you please run:
```
SELECT id from nostrmarket.merchants WHERE public_key='...'
```
- do you get any result back?

**Comment by motorina0** [comment]
- there is the constraint of a merchant key being unique per LNbits instance.
- this means a particular merchant will only be managed by one LNbits user.
- having different users manage the same merchant can lead to synchronization issues for product updates and orders.

**Comment by arbadacarbaYK** [comment]
Not at home atm but.. actually it got lost - thats why i wanted to import it again. 
The scenario was full of errors, so let me show you and explain

Aaron informed me that a change of Admins under Manage Server makes the "Manage Server" link dissappear.
When i checked that on my node i found the same behaviour - on top the market got deleted.

Then i wanted to update the extension and this again lead to a dissappearing Manage Server section (until reboot, but was after reboot available) 
So i guess its still in the db (not home atm) but invisible in the gui :P


<img width="1330" alt="Bildschirmfoto 2023-05-07 um 19 53 31" src="https://user-images.githubusercontent.com/63317640/236768999-409fa0d9-e711-49c3-b62e-ea1a64853839.png">

<img width="1085" alt="Bildschirmfoto 2023-05-07 um 20 01 35" src="https://user-images.githubusercontent.com/63317640/236768994-94465da1-6fc0-46f6-8915-b250a7b12120.png">

<img width="1219" alt="Bildschirmfoto 2023-05-07 um 20 01 59" src="https://user-images.githubusercontent.com/63317640/236768987-d34bf27f-cbb6-41e3-ac0c-00b6ea9f5329.png">

<img width="954" alt="Bildschirmfoto 2023-05-07 um 20 03 58" src="https://user-images.githubusercontent.com/63317640/236768984-18756009-a558-4044-9ad7-a398beac4027.png">

<img width="652" alt="Bildschirmfoto 2023-05-07 um 20 16 06" src="https://user-images.githubusercontent.com/63317640/236768980-88485f69-d2e7-476e-a84b-d97442010549.png">


Also tried you communication button and it didnt transport the event. My market was before shown on legend and my own market.

**Comment by arbadacarbaYK** [comment]
I am on Citadel. Aaron presumed it could have to do with dockerizing

**Comment by motorina0** [comment]
> I am on Citadel. Aaron presumed it could have to do with dockerizing

I hope the instance is NOT publicly available, otherwise please remove the screenshots with user IDs ASAP!

**Comment by arbadacarbaYK** [comment]
its not but for the sake of it deleted. you got the point.

**Comment by arbadacarbaYK** [comment]
If the superuser-ID is put into the admin-users the described behaviour does not happen (manage server on superuser-url not anylonger available after change of extensions/allowed users/admins). Isnt the superuser also an admin by default ? :P

**Comment by motorina0** [comment]
* do you have the possibility of executing SQL queries?  If yes, can you please run:

```
SELECT id from nostrmarket.merchants WHERE public_key='...'
```

* do you get any result back?
