### ISSUE TITLE
[Feature request] Option to download digital item

### ISSUE THREAD

**Issue by Darth-Coin** [lnbits/nostrmarket#59]
### Description
Yes, we have a nice market, selling digital items (files, pictures, audiio/video files). We can add nice pictures representing them.
But how the customer, after paying, will get a link to download the file that just bought?

We need an option, that the item is created, also the file is uploaded to a repository (NAS, Nextcloud, GDrive, gofile.io) and the customer could just get the link after the payment.

Right now all the process is manual, merchant have to send the link to the customer, through nostr chat or email.

Maybe something simple like this, to start. And when customer pays, will receive a nostr message with the link and also by email if was provided in the order.
![image](https://user-images.githubusercontent.com/56997124/236874640-6524c955-5eca-4620-973a-9e97367224d2.png)

**Comment by protocoel** [comment]
Can nostr support selling NFTs? Off topic, sorry.

**Comment by motorina0** [comment]
> Can nostr support selling NFTs? Off topic, sorry.

Depends on what the NFT is. Is it digital content? A JPEG? Some random data that provides ownership?

The next release will support the request in this particular issue.

**Comment by motorina0** [comment]
Done. Auto-reply on payment is now an option.
The merchant can auto-reply with the link for the digital good.
