### ISSUE TITLE
Possibility to group merchants and their stalls into a "Shopping Mall" in Nostrmarket

### ISSUE THREAD

**Issue by Satoshi-Samourai** [lnbits/nostrmarket#60]
I would like to propose a feature that will allow LNBits super user or admin accounts to group other merchants on their LNBits instance into something like a "Shopping Mall". The super user/admin could than share a link/pubkey which makes the Shopping Mall accessable to others with one click. This link could than be bookmarked and reused without uploading specific relays and merchant's IDs everytime one wants to go "shopping"

My uses case is a comunity of bitcoin accepting merchants in a specific area (around 30 merchants). Now, i want to bring them together in what I call a "Shopping Mall". Everybody has to create his own merchant instance and stall (on my LNBits on my node) but needs only one link to see everybody else. I am the one who is adding these links together into a "Shopping Mall". Something like "the one place to go to find everybody who accepts bitcoin in my area".

Thank you very much for considering.

**Comment by motorina0** [comment]
- this has been implemented with PR: https://github.com/lnbits/nostrmarket/pull/41
- this manifest can be used to access the latest version: https://raw.githubusercontent.com/lnbits/nostrmarket/main/manifest.json
- short demo:

https://github.com/lnbits/nostrmarket/assets/2951406/445b553b-a42f-43a0-8bf5-04071f84ad45
