### ISSUE TITLE
product deleted but keep showing up in market public 

### ISSUE THREAD

**Issue by W6Design** [lnbits/nostrmarket#61]
Nice project :) 

I've setup a stall, add a product , but when i wanted to update the picture , it didn't go well so i add another product and delete the first one .

in the lnbits extension manager, all looks great , but i can still see the deleted product : https://sadruffs4.lnbits.com/nostrmarket/market?merchant_pubkey=81cce63772699677ec45559da11ea7c2eac842f02411efa0d558ae8f325ec855&stall_id=LBoXPKu3VUNYPEYswbZqCM&product_id=YsRUqoBFZhJeLLvFT9nVHA

I did delete all nostr posts and re-publish .

**Comment by motorina0** [comment]
Thanks!
- I see two products in the marketplace. Should there be only one?
- Do you have the same view as the screenshot?

![image](https://github.com/lnbits/nostrmarket/assets/2951406/10c186de-2572-4cae-8120-aeae81deaee8)

**Comment by W6Design** [comment]
I have the same view and there should be only the pineco 04 ( I deleted the pineco 1 ) . 

here is a view of the current nostr market stall admin view 

maybe i can send you the database dump ? 

![Capture d’écran 2023-05-30 145540](https://github.com/lnbits/nostrmarket/assets/4004560/8a0d80ea-3272-4139-8419-805d9c82928c)

**Comment by talvasconcelos** [comment]
Can it be that the product didn't get deleted from at least 1 relay, and it get's pulled in?

**Comment by motorina0** [comment]
> Can it be that the product didn't get deleted from at least 1 relay, and it get's pulled in?

No. I have tested with only one relay (wss://relay.damus.io) and the product still shows up.

**Comment by motorina0** [comment]
A bit pricey, but other than that you didn't do anything wrong. I'm trying to reproduce the issue locally.

**Comment by W6Design** [comment]
It's unique ceramic art but you're right, we will certainly reduce the price, especially to test a real selling from this channel :)

also, i don't know how to integrate  in nostr ( just link ? )

**Comment by motorina0** [comment]
With the new changes to the marketplace you will be able to restore from nostr your stalls and products.
Then you can update/delete them if you want.

In the video below I have mocked your pubkey and restored your stall. I was able to restore both products. Of course I could not delete the old one since I do not have the private key.

There changes are on `main` and there is a `pre-release` if you want to test:

https://github.com/lnbits/nostrmarket/assets/2951406/d8389463-c63f-4a8b-8c0d-708b41d81fb1
