### ISSUE TITLE
Nostr Market extension makes external http calls and attempts to execute foreign javascript

### ISSUE THREAD

**Issue by gStart9** [lnbits/nostrmarket#76]
I'm trying to "self-host" lnbits and to that end, was inspecting the "Nostr Marketplace" extension and see it trying to make unauthorized calls to internet resources, pulling in javascript from external sources such as unpkg.com and cdn.jsdelivr.net for some unknown reason:
![image](https://github.com/lnbits/nostrmarket/assets/106188942/d47378a3-7fad-4226-9f40-b290ac8040f3)

Will this be easy to bring this externally-hosted javascript into the self-hosting environment?  Seems to me like a notable privacy and security issue.

Thanks

FYI this seems to be a problem with the regular "marketplace" plugin as well, which I also made [an issue](https://github.com/lnbits/market/issues/12) for earlier today.

**Comment by motorina0** [comment]
Thank you!
I'm checking this now.

**Comment by talvasconcelos** [comment]
These are the js nostr tools and the js image processing tool, which are used in nostrmarket extension and i guess offline shop extension. We can probably bring those JS files into the extension... if it makes sense

**Comment by motorina0** [comment]
- a new release is available at https://raw.githubusercontent.com/lnbits/nostrmarket/v0.3.6/manifest.json
- this release is not yet on the vetted extensions repo
- in the new release the external JS resources are being served locally abd the new version of the marketplace is available
