### ISSUE TITLE
Don't overload event kinds

### ISSUE THREAD

**Issue by staab** [lnbits/nostrmarket#8]
Please don't put json in kind-1 events, instead propose new kinds to support your use case.

**Comment by motorina0** [comment]
- this extension does not use `kind: 1` at all
- it uses [Parameterized Replaceable Events](https://github.com/nostr-protocol/nips/blob/master/33.md)
   - kind 30017 & 30018
   - see example here: https://www.nostr.guru/e/0dc525844988d44e42cccdee41ae7442552019efd1b724856c6126dcd0dbada1
