### ISSUE TITLE
Unable to checkout - JavaScript / Vue Errors

### ISSUE THREAD

**Issue by blackcoffeexbt** [lnbits/nostrmarket#80]
When checking out on the store linked below (legend) I'm not able to complete the process. I add my private / pub key to the checkout form and click "Checkout". On clicking checkout, there is no change in the UI, but I can see JS errors in the dev console. 

Stall: https://legend.lnbits.com/nostrmarket/market?merchant_pubkey=a7e8069e57ec8ff359d994621e8a492930f1a2ea3f862629e54e2ed627d182e8&stall_id=cAKpWpxTCZpcRQ5ZG2Jydo

Images attached

![image](https://github.com/lnbits/nostrmarket/assets/87530449/4ed26678-04a2-4dd0-bd79-6bfd1837c6d5)

Chrome console log here 
[legend.lnbits.com-1693476592945.log](https://github.com/lnbits/nostrmarket/files/12485024/legend.lnbits.com-1693476592945.log)

**Comment by motorina0** [comment]
This is an old UI. Please check: https://lnbits.github.io/nostr-market-app/market/#/

![image](https://github.com/lnbits/nostrmarket/assets/2951406/cc10a55e-5836-4d9c-8c86-04dceecc1659)

**Comment by blackcoffeexbt** [comment]
@motorina0 should the market client be removed / updated in the extension sidebar?

![Screenshot_20230904-090228~3](https://github.com/lnbits/nostrmarket/assets/87530449/5f6b3a1f-4754-420e-9344-031339f72429)

**Comment by motorina0** [comment]
> @motorina0 should the market client be removed / updated in the extension sidebar?

- no, in the new version of the extension the same SPA (as the one here https://lnbits.github.io/nostr-market-app/market/#/) is hosted and served from the LNbits extension (the link works)
- this is in case the users of the market do not want to access a public page
