### ISSUE TITLE
where do I find the market profile naddr?

### ISSUE THREAD

**Issue by diskbuster** [lnbits/nostrmarket#90]
I am looking for the naddr to share a market profile, but I can't find it in 0.5 or 0.5.1.

Every time I use the "Share market profile" link, I get a feedback that the profile was published to my relais - but no naddr link.

Did I miss something, or is this a bug?

**Comment by motorina0** [comment]
Its a UX problem.
When you click `Share market profile` the `naddr` is copied to your clipboard (and a toasty message is shown).
But the flow should be more explicit.

Leaving this issue open.

**Comment by diskbuster** [comment]
Thanks for the info! In Chrome it works fine. In Safari i get nothing copied in the clipboard, but an error message:

```
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonyme Funktion) (MarketPage.e81dd906.js:45:36709)
```

would also be nice to have a tiny copy to clipboard button for the naddr.
