### ISSUE TITLE
Bug: long product names in the order summary overlap with the price.

### ISSUE THREAD

**Issue by rleed** [lnbits/nostrmarket#91]
Ran into this during production today. See overlapping text in the following image:
![image](https://github.com/lnbits/nostrmarket/assets/101502594/9e679563-7d94-49d5-ba16-a1e984e96f0f)

I think wrapping the product name to multiple lines would be fine.

**Comment by motorina0** [comment]
Fixed. Will be included in the next release.

![image](https://github.com/lnbits/nostrmarket/assets/2951406/4f3f3ef2-a285-4215-ae05-e99d77489f16)
